### PR TITLE
Script to generate a PostgreSQL schema from GTFS

### LINKED ISSUE #1: Pre-processing script to dynamically create a schema from a GTFS feed
This seems like it would be straightforward to me. Are there any challenges to this approach?

### PR DESCRIPTION
**Pull request by hfs**
This implements the idea already mentioned in the README.md: Write a script to generate a schema based on the contents of an actual GTFS file.

The bash script acts on a directory with the extracted contents of a GTFS file.  It checks which files are present and prepares one table for each of them.  Then it checks which columns are present and in which order and generates a column defintiion for each of them. Finally, the contents of the CSV files are imported into the database using PostgreSQL's \COPY mode.

Closes #1

### CODE REVIEW

**Comment by tyleragreen** [comment]
This seems fantastic @hfs! Is there a bash version requirement?

I am running the following command on `3.2.57(1)-release` of bash for macOS High Sierra.
```
./gtfs_schema.sh ~/Downloads/mbta_gtfs/ > mbta_schema.sql
```

where `~/Downloads/mbta_gtfs` is the unzipped data from [MBTA GTFS from OpenMobilityData](http://transitfeeds.com/p/mbta/64/latest/download).

I receive the following errors:
```
./gtfs_schema.sh: line 35: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./gtfs_schema.sh: line 180: agency.txt/agency_id: syntax error: invalid arithmetic operator (error token is ".txt/agency_id")
./gtfs_schema.sh: line 299: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./gtfs_schema.sh: line 305: agency.txt/agency_idnagency_namenagency_ulnagency_timezonenagency_langnagency_phone: syntax error: invalid arithmetic operator (error token is ".txt/agency_idnagency_namenagency_ulnagency_timezonenagency_langnagency_phone")
./gtfs_schema.sh: line 314: agency.txt/agency_name: syntax error: invalid arithmetic operator (error token is ".txt/agency_name")
./gtfs_schema.sh: line 329: agency.txt/agency_idnagency_namenagency_ulnagency_timezonenagency_langnagency_phone: syntax error: invalid arithmetic operator (error token is ".txt/agency_idnagency_namenagency_ulnagency_timezonenagency_langnagency_phone")
```

**Comment by hfs** [comment]
Yes, the script requires bash version >= 4. `declare -A` creates an associative array, a feature which was introduced with bash 4.0. I went with bash because I thought it’s ubiquitous… didn’t know about macOS.

Do you have the option of installing bash 4 as additional package via e.g. Homebrew or Macports?

I could add a version check with an explanation at the top of the script if you want?

Alternatively I could try to rewrite it using only bash 3, but then the script would become quite ugly.

**Comment by tyleragreen** [comment]
Got it! I was able to confirm functionality using bash 5.0 in the image from Dockerhub. Very cool! 🙌 

I don't think we need a version check in the script. Want to just throw the version requirement into the README and this will be good to go?

**Comment by hfs** [comment]
Sure, I added a note to the README

**Review by tyleragreen — APPROVED** [review]
Thanks @hfs 🙌

**Pull request merged**
